server:
  port: 8090

Spring:
  application:
    name: mueblesstgo_app
  jpa:
    show-sql: true
    hibernate:
      dialect: MySQL8Dialect
      ddl-auto: create-drop
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3307/mueblesstgo_app
    username: root
    password: Chile&2022
    #url: ${DB_URL}
    #username: ${DB_USERNAME}
    #password=: ${DB_PASSWORD}